name: C/C++ CI

on:
  push:
    branches: [ master ]
    tags:
      - v*.*
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: [self-hosted, Linux]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: ./compile.sh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sdl2_renderer_test
        path: sdl2_renderer_test
    - uses: actions/upload-artifact@v3
      with:
        name: sdl2_pixelformat_test
        path: sdl2_pixelformat_test
    - name: Deploy
      uses: actions/download-artifact@v3.0.0
      with:
        name: sdl2_renderer_test
        path: ~/projects
    - uses: actions/download-artifact@v3.0.0
      with:
        name: sdl2_pixelformat_test
        path: ~/projects
    - name: Release
      uses: ncipollo/release-action@v1
      if: github.ref_type == 'tag'
      with:
        allowUpdates: true
        artifacts: |
          sdl2_pixelformat_test
          sdl2_renderer_test
    
