name: C/C++ CI

on:
  push:
    branches: [ master ]
    tags:
      - v*.*
  pull_request:
    branches: [ master ]
  
jobs:
  git-tag:
    runs-on: [self-hosted]
    outputs:
      tag_name: ${{ steps.vars.outputs.TAG_NAME }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Set output
        id: vars
        run: echo ::set-output name=TAG_NAME::$(git describe --abbrev=0)

  build:
    needs: git-tag
    runs-on: [self-hosted, Linux]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: ./compile.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sdl2_renderer_test
        path: sdl2_renderer_test
    - uses: actions/upload-artifact@v3
      with:
        name: sdl2_pixelformat_test
        path: sdl2_pixelformat_test
    - name: ZIP binaries
      if: github.ref_type == 'tag'
      run: zip sdl2_tests-${{ needs.git-tag.outputs.tag_name }}.zip sdl2_pixelformat_test sdl2_renderer_test

    - name: Release
      if: github.ref_type == 'tag'
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        generateReleaseNotes: true
        artifacts: |
          sdl2_tests-${{ needs.git-tag.outputs.tag_name }}.zip
    
