name: C/C++ CI

on:
  push:
    branches: [ master ]
    tags:
      - v*.*
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: [self-hosted, Linux]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: ./compile.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sdl2_renderer_test
        path: sdl2_renderer_test
    - uses: actions/upload-artifact@v3
      with:
        name: sdl2_pixelformat_test
        path: sdl2_pixelformat_test

    - name: Get tag
      if: github.ref_type == 'tag'
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        # Optionally strip `v` prefix
        strip_v: false

    - name: ZIP binaries
      if: github.ref_type == 'tag'
      run: zip sdl2_tests-${{ steps.tag.outputs.tag }}.zip sdl2_pixelformat_test sdl2_renderer_test

    - name: Create changelog text
      if: github.ref_type == 'tag'
      id: changelog
      uses: loopwerk/tag-changelog@v1
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/tag-changelog-config.js

    - name: Release
      if: github.ref_type == 'tag'
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        omitBodyDuringUpdate: true
        body: ${{ steps.changelog.outputs.changes }}
        artifacts: |
          sdl2_tests-${{ steps.tag.outputs.tag }}.zip
    
